import Munkres.Mathlib.Prelude

open Set TopologicalSpace

universe u

variable {α : Type u} {B : Set (Set α)}

section DefiningABasis

-- The reason why we reduce all finite intersection arguments to just the
-- intersection of two elements — that we can extend it to finite intersections
-- by induction.
example {B : Set (Set α)}
  (h : ∀ b₁ ∈ B, ∀ b₂ ∈ B, b₁ ∩ b₂ ∈ B)
  (h_univ : univ ∈ B)
  : ∀ s ⊆ B, s.Finite → ⋂₀ s ∈ B
  := by --
  intro s hsB hsF
  induction s, hsF using Set.Finite.induction_on with
  | empty =>
    rw [sInter_empty]
    exact h_univ
  | @insert u s hus hsF ih =>
    have huB : u ∈ B := hsB <| mem_insert u s
    if hs₀ : s = ∅ then
      subst hs₀
      simp only [insert_empty_eq, sInter_singleton]
      exact huB
    else
    replace hs₀ : s.Nonempty := nonempty_iff_ne_empty.mpr hs₀
    specialize ih ((subset_insert u s).trans hsB)
    rw [sInter_insert u s]
    exact h u huB _ ih -- ∎

variable
  (h₁ : ∀ x, ∃ b ∈ B, x ∈ b)
  (h₂ : ∀ b₁ ∈ B, ∀ b₂ ∈ B, ∀ x ∈ b₁ ∩ b₂, ∃ b ∈ B, x ∈ b ∧ b ⊆ b₁ ∩ b₂)

private lemma l₀ {U : Set α} :
  (∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U) → ∃ s ⊆ B, U = ⋃₀ s
  := by --
  intro h
  let hp (x : U) : Set α := (h x x.prop).choose
  let s := Set.range hp
  use Set.range hp
  refine ⟨?_, ?_⟩
  · intro _ ⟨x, heq⟩
    subst heq
    exact (h x x.prop).choose_spec.1
  · rw [Set.sUnion_range]
    ext x : 1
    rw [Set.mem_iUnion]
    refine ⟨?_, ?_⟩
    · intro hx
      exact ⟨⟨x, hx⟩, (h x hx).choose_spec.2.1⟩
    · intro ⟨y, hy⟩
      exact (h y y.prop).choose_spec.2.2 hy -- ∎

include h₁ h₂ in
private lemma l₁
  : ∀ U, @IsOpen α (generateFrom B) U → ∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U
  := by --
  intro U h x hx
  induction h with
  | basic b hb =>
    exact ⟨b, hb, hx, le_rfl⟩
  | univ =>
    obtain ⟨b, h⟩ := h₁ x
    exact ⟨b, h.1, h.2, Set.subset_univ _⟩
  | inter u₁ u₂ _ _ hu₁ hu₂ =>
    obtain ⟨b₁, hb₁, hx₁, hu₁⟩ := hu₁ hx.1
    obtain ⟨b₂, hb₂, hx₂, hu₂⟩ := hu₂ hx.2
    specialize h₂ b₁ hb₁ b₂ hb₂ x ⟨hx₁, hx₂⟩
    obtain ⟨b, hbB, hxb, hb⟩ := h₂
    refine ⟨b, hbB, hxb, ?_⟩
    rw [Set.subset_inter_iff] at hb ⊢
    exact ⟨hb.1.trans hu₁, hb.2.trans hu₂⟩
  | sUnion s _ hs =>
    obtain ⟨u, hus, hxu⟩ := hx
    specialize hs u hus hxu
    obtain ⟨b, hbB, hxb, hbu⟩ := hs
    refine ⟨b, hbB, hxb, ?_⟩
    refine hbu.trans ?_
    exact Set.subset_sUnion_of_subset s u le_rfl hus -- ∎

private lemma l₂
  : ∀ U, (∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U) → @IsOpen α (generateFrom B) U
  := by --
  intro U h
  obtain ⟨s, hs, heq⟩ := l₀ h
  subst heq
  refine GenerateOpen.sUnion s ?_
  intro u hu
  refine GenerateOpen.basic u ?_
  exact hs hu -- ∎

include h₁ h₂ in
/-- Here's how Munkres defines the topology generated by a basis. In particular,
`T = generateFrom B` -/
private lemma l₃ {U : Set α}
  : @IsOpen α (generateFrom B) U ↔ ∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U
  := ⟨l₁ h₁ h₂ U, l₂ U⟩

end DefiningABasis

section S₁
--* Lemma 13.1
variable [TopologicalSpace α] (hB : IsTopologicalBasis B)

-- In other words, 𝓣 = collection of all unions of elements of 𝓑.
example {U : Set α} : IsOpen U ↔ ∃ s ⊆ B, U = ⋃₀ s  := by
  refine ⟨?_, ?_⟩
  · intro hU
    rw [hB.isOpen_iff] at hU
    exact l₀ hU
  · intro ⟨s, hs, heq⟩
    subst heq
    refine isOpen_sUnion ?_
    intro u hu
    exact hB.isOpen (hs hu)

end S₁

section S₂
--* Lemma 13.2
variable [TopologicalSpace α] {C : Set (Set α)}
  (h₁ : ∀ c ∈ C, IsOpen c)
  (h₂ : ∀ u, IsOpen u → ∀ x ∈ u, ∃ c ∈ C, x ∈ c ∧ c ⊆ u)

example : IsTopologicalBasis C
  := by --
  have h₃ : ∀ x, ∃ b ∈ C, x ∈ b := by
    intro x
    obtain ⟨c, hcC, hxc, _⟩ := h₂ Set.univ isOpen_univ x trivial
    exact ⟨c, hcC, hxc⟩
  have h₄ : ∀ s ∈ C, ∀ t ∈ C, ∀ x ∈ s ∩ t, ∃ c ∈ C, x ∈ c ∧ c ⊆ s ∩ t := by
    intro s hs t ht x hx
    exact h₂ (s ∩ t) ((h₁ s hs).inter (h₁ t ht)) x hx
  exact {
    sUnion_eq := Set.sUnion_eq_univ_iff.mpr h₃
    exists_subset_inter := h₄
    eq_generateFrom := by
      refine TopologicalSpace.ext ?_
      ext u : 2
      rw [l₃ h₃ h₄]
      refine ⟨h₂ u, ?_⟩
      intro h
      obtain ⟨s, hs, heq⟩ := l₀ h
      subst heq
      exact isOpen_sUnion fun t ht ↦ h₁ t (hs ht)
  } -- ∎

end S₂

section S₃
--* Lemma 13.2
variable [T : TopologicalSpace α] [T' : TopologicalSpace α]
  {B B' : Set (Set α)}
  (hB : IsTopologicalBasis (t := T) B)
  (hB' : IsTopologicalBasis (t := T') B')

-- Note that T' is finer than T here.
example : T' ≤ T ↔ ∀ x, ∀ b ∈ B, x ∈ b → ∃ b' ∈ B', x ∈ b' ∧ b' ⊆ b
  := by --
  constructor
  · intro hle x b hbB hxb
    have hb : @IsOpen α T b := hB.isOpen (t := T) hbB
    have hb' : @IsOpen α T' b := hle b hb
    rw [hB'.isOpen_iff] at hb'
    exact hb' x hxb
  · intro h u hu
    rw [hB.isOpen_iff (t := T)] at hu
    rw [hB'.isOpen_iff]
    intro x hx
    obtain ⟨b, hbB, hxb, hbu⟩ := hu x hx
    obtain ⟨b', hbB', hxb', hbb⟩ := h x b hbB hxb
    exact ⟨b', hbB', hxb', hbb.trans hbu⟩ -- ∎

end S₃
